Clarify interop with pre-1.3 cipher suite registry
tlswg/draft-ietf-tls-iana-registry-updates pull request #68
Opened 2018-04-02 12:49 UTC by richsalz

2018-04-05 02:03 UTC, kaduk requested changes
The registered ciphersuite values have always been distinct two-octet values, with no internal structure or interpretation to the separate octets.

A similar statement to this might be relevant for the SignatureScheme registry, which combines the preexisting SignatureAlgorithm and HashAlgorithm codepoint spaces into a new registry without internal structure going forward but constrained by historical legacy.

2018-04-05 11:33 UTC, richsalz commented
I was focused on interop, I don't see where/how to put that sentence you want.

2018-04-05 12:59 UTC, richsalz commented
Did I get the 1.2/1.3 bytes backwards, hence Sean's confusion?

2018-04-06 22:12 UTC, jsalowey commented on draft-ietf-tls-iana-registry-updates.md
> +suites. Therefore, registraries for TLS 1.2 and earlier may require
Should this be **registrations?**

2018-04-06 22:19 UTC, jsalowey commented on draft-ietf-tls-iana-registry-updates.md
> +suites. Therefore, registraries for TLS 1.2 and earlier may require
I don't understand where the requirement to reserve and entire byte range in TLS 1.2 comes from?  Can you elaborate?

2018-05-23 03:15 UTC, jsalowey commented
I think this pull request should be closed as it is not correct.

2018-05-23 14:10 UTC, closed without merging